spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.8bdfc95331229209
            clientSecret: 5791268dc97417041475e75cec40112d915b942c
          google:
            clientId: 478010581524-9i3baqf0bsa1pq9dilr3s70igv44tk4j.apps.googleusercontent.com
            clientSecret: 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